### ISSUE TITLE
The 'Deposit' function is not necessary.

### ISSUE THREAD

**Issue by vatsal095** [holdex/payment-streaming#116]
In the **Deposit** function, only the **safeTransferFrom()** function is called, and there is no state update within the deposit function. Therefore, there is no need for **safeTransferFrom()**. Instead, you can use **transfer()** directly to the smart contract, as both methods achieve the same result and are gas-efficient.
**transfer()**: 2300 gas, 
**safeTransferFrom()**: 50,000 gas

**Comment by call3hudson** [comment]
@vatsal095 Would you kindly let us know where you found the **transfer()** function only consumes 2300 gas? (seems you've confused eth transfer and erc20 transfer)
The **deposit** function is definitely needed because it triggers **deposit** event which can be then filtered off-chain like thegraph etc. Event is a very important term in smart contracts so it's important to expose external APIs.

**Comment by vatsal095** [comment]
You're correct; we do need a deposit function.
